
services:

  flask:
    build: .
    container_name: flask-app
    ports:
      - "80:5000"

    environment:
      MYSQL_HOST: mysql-db
      MYSQL_USER: Ahmad
      MYSQL_PASSWORD: root
      MYSQL_DB: devops

    depends_on:
      mysql:
        condition: service_healthy

    networks:
      - two-tier

  mysql:
    image: mysql:8.4
    container_name: mysql-db

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devops
      MYSQL_USER: Ahmad
      MYSQL_PASSWORD: root

    volumes:
      - mysql_data:/var/lib/mysql

    healthcheck:
      test:
        [
          "CMD",
          "mysql",
          "-h",
          "localhost",
          "-uAhmad",
          "-proot",
          "-e",
          "SELECT 1",
          "devops"
        ]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 30s

    networks:
      - two-tier


networks:
  two-tier:
    driver: bridge


volumes:
  mysql_data:

